[package]
name = "base"
version = "1.0.0"
authors = ["Near Inc <hello@near.org>"]
edition = "2021"

[package.metadata.near.reproducible_build]
build_environment.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = { version = "5.1.0", features = ["legacy"] }
